version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - milvus-standalone
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MILVUS_HOST=milvus-standalone
      - MILVUS_PORT=19530
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HF_API_KEY=${HF_API_KEY}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - LLM_PROVIDER=${LLM_PROVIDER:-lmstudio}
      - DEBUG=true
    volumes:
      - ./app:/app/app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  milvus-standalone:
    image: milvusdb/milvus:v2.2.3
    container_name: milvus-standalone
    command: ["milvus", "run", "standalone"]
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - etcd
      - minio

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: milvus-etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    volumes:
      - etcd_data:/etcd

  minio:
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    container_name: milvus-minio
    volumes:
      - minio_data:/data
    command: minio server /data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mongo_data:
  milvus_data:
  etcd_data:
  minio_data: